In [1]:
# Importing basic libraries for data manipulation and analysis
import pandas as pd # For data manipulation and analysis

# Setting up display options
pd.set_option('display.max_columns', None)  # Display all columns in DataFrame
pd.set_option('display.max_rows', 100)  # Set the number of rows to display
sns.set(style="whitegrid")  # Set Seaborn style for plots

# Warnings
import warnings
warnings.filterwarnings("ignore")  # Ign

In [10]:
df = pd.read_csv("/Users/Jamie/OneDrive/Documents/python_ws/project_delta/data/raw_data/retail_data.csv")

In [11]:
df.head()

,customer_id,age,gender,income_bracket,loyalty_program,membership_years,churned,marital_status,number_of_children,education_level,occupation,transaction_id,transaction_date,product_id,product_category,quantity,unit_price,discount_applied,payment_method,store_location,transaction_hour,day_of_week,week_of_year,month_of_year,avg_purchase_value,purchase_frequency,last_purchase_date,avg_discount_used,preferred_store,online_purchases,in_store_purchases,avg_items_per_transaction,avg_transaction_value,total_returned_items,total_returned_value,total_sales,total_transactions,total_items_purchased,total_discounts_received,avg_spent_per_category,max_single_purchase_value,min_single_purchase_value,product_name,product_brand,product_rating,product_review_count,product_stock,product_return_rate,product_size,product_weight,product_color,product_material,product_manufacture_date,product_expiry_date,product_shelf_life,promotion_id,promotion_type,promotion_start_date,promotion_end_date,promotion_effectiveness,promotion_channel,promotion_target_audience,customer_zip_code,customer_city,customer_state,store_zip_code,store_city,store_state,distance_to_store,holiday_season,season,weekend,customer_support_calls,email_subscriptions,app_usage,website_visits,social_media_engagement,days_since_last_purchase
0,1,56,Other,High,No,0,No,Divorced,3,Bachelor's,Self-Employed,503290,2020-10-11 10:08:52,1480,Electronics,8,49.72,0.50,Credit Card,Location A,18,Wednesday,27,7,411.13,Weekly,2021-09-11 04:22:38,0.02,Location A,55,86,8.64,171.83,0,750.40,563.16,69,367,415.01,114.28,679.25,0.28,Product D,Brand Y,2.5,560,48,0.40,Small,4.61,Red,Metal,2019-08-04 01:47:01,2022-05-28 14:54:02,250,271,20% Off,2021-07-14 14:28:42,2022-12-30 13:04:13,High,Online,New Customers,37848,City D,State Y,88500,City D,State Y,33.21,No,Spring,Yes,5,No,High,30,High,40
1,2,69,Female,Medium,No,2,No,Married,2,PhD,Unemployed,347796,2021-12-08 01:07:40,1597,Groceries,7,817.76,0.32,Credit Card,Location C,15,Friday,20,2,268.71,Daily,2021-05-16 12:01:16,0.33,Location C,48,2,9.60,20.18,4,551.60,7554.57,8,475,801.79,305.95,491.56,4.65,Product C,Brand X,4.7,413,80,0.30,Medium,0.84,Blue,Metal,2019-10-23 19:59:17,2022-12-19 08:04:41,180,631,Flash Sale,2021-09-23 04:26:09,2022-09-13 03:16:26,Low,Social Media,New Customers,44896,City A,State X,30046,City C,State X,62.56,No,Summer,Yes,6,No,High,40,Medium,338
2,3,46,Female,Low,No,5,No,Married,3,Bachelor's,Self-Employed,493688,2020-02-17 09:40:48,5142,Toys,8,270.30,0.35,Debit Card,Location A,9,Saturday,35,6,246.79,Weekly,2021-02-07 16:47:48,0.47,Location B,16,45,1.55,55.17,0,629.19,7564.14,73,138,264.31,426.70,938.26,7.30,Product B,Brand X,4.6,312,14,0.08,Medium,0.23,Green,Plastic,2018-05-12 08:00:29,2023-02-01 12:15:07,131,879,Flash Sale,2021-06-13 12:31:15,2022-03-13 00:53:35,Low,Online,New Customers,11816,City B,State X,26169,City A,State Y,83.04,Yes,Winter,Yes,2,Yes,Low,89,Medium,61
3,4,32,Female,Low,No,0,No,Divorced,2,Master's,Employed,861348,2020-08-13 00:43:14,8447,Toys,2,547.84,0.10,Credit Card,Location A,13,Friday,42,8,178.92,Weekly,2021-12-30 23:48:26,0.41,Location B,50,47,1.78,15.79,3,346.67,8125.92,20,158,192.93,689.58,644.31,7.31,Product A,Brand Z,1.1,110,69,0.09,Large,4.37,Blue,Wood,2019-11-15 16:17:29,2023-02-05 11:46:57,16,211,Buy One Get One Free,2021-05-23 05:42:48,2022-02-06 00:42:30,High,Social Media,Returning Customers,78604,City A,State Y,22667,City B,State Z,50.43,Yes,Winter,No,12,No,Low,12,Low,42
4,5,60,Female,Low,Yes,7,Yes,Divorced,2,Bachelor's,Employed,535835,2021-07-02 11:59:03,6025,Clothing,4,785.29,0.17,Mobile Payment,Location C,17,Monday,37,3,214.06,Yearly,2021-11-02 11:48:25,0.22,Location B,48,42,9.38,240.03,2,979.91,114.32,83,263,497.26,715.86,162.86,1.92,Product C,Brand X,3.8,172,25,0.39,Small,1.68,Red,Metal,2019-08-27 02:58:19,2023-10-05 08:13:07,57,862,Flash Sale,2021-04-19 04:55:32,2022-12-04 13:07:09,Medium,Online,New Customers,17760,City B,State Z,87843,City C,State X,36.55,Yes,Summer,Yes,3,No,Medium,31,Low,242

In [12]:
df.shape

(1000000, 78)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 78 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   customer_id                1000000 non-null  int64
 1   age                        1000000 non-null  int64
 2   gender                     1000000 non-null  object
 3   income_bracket             1000000 non-null  object
 4   loyalty_program            1000000 non-null  object
 5   membership_years           1000000 non-null  int64
 6   churned                    1000000 non-null  object
 7   marital_status             1000000 non-null  object
 8   number_of_children         1000000 non-null  int64
 9   education_level            1000000 non-null  object
 10  occupation                 1000000 non-null  object
 11  transaction_id             1000000 non-null  int64
 12  transaction_date           1000000 non-null  object
 13  product_id                 1000000 non-null  int64
 14  product_category           1000000 non-null  object
 15  quantity                   1000000 non-null  int64
 16  unit_price                 1000000 non-null  float64
 17  discount_applied           1000000 non-null  float64
 18  payment_method             1000000 non-null  object
 19  store_location             1000000 non-null  object
 20  transaction_hour           1000000 non-null  int64
 21  day_of_week                1000000 non-null  object
 22  week_of_year               1000000 non-null  int64
 23  month_of_year              1000000 non-null  int64
 24  avg_purchase_value         1000000 non-null  float64
 25  purchase_frequency         1000000 non-null  object
 26  last_purchase_date         1000000 non-null  object
 27  avg_discount_used          1000000 non-null  float64
 28  preferred_store            1000000 non-null  object
 29  online_purchases           1000000 non-null  int64
 30  in_store_purchases         1000000 non-null  int64
 31  avg_items_per_transaction  1000000 non-null  float64
 32  avg_transaction_value      1000000 non-null  float64
 33  total_returned_items       1000000 non-null  int64
 34  total_returned_value       1000000 non-null  float64
 35  total_sales                1000000 non-null  float64
 36  total_transactions         1000000 non-null  int64
 37  total_items_purchased      1000000 non-null  int64
 38  total_discounts_received   1000000 non-null  float64
 39  avg_spent_per_category     1000000 non-null  float64
 40  max_single_purchase_value  1000000 non-null  float64
 41  min_single_purchase_value  1000000 non-null  float64
 42  product_name               1000000 non-null  object
 43  product_brand              1000000 non-null  object
 44  product_rating             1000000 non-null  float64
 45  product_review_count       1000000 non-null  int64
 46  product_stock              1000000 non-null  int64
 47  product_return_rate        1000000 non-null  float64
 48  product_size               1000000 non-null  object
 49  product_weight             1000000 non-null  float64
 50  product_color              1000000 non-null  object
 51  product_material           1000000 non-null  object
 52  product_manufacture_date   1000000 non-null  object
 53  product_expiry_date        1000000 non-null  object
 54  product_shelf_life         1000000 non-null  int64
 55  promotion_id               1000000 non-null  int64
 56  promotion_type             1000000 non-null  object
 57  promotion_start_date       1000000 non-null  object
 58  promotion_end_date         1000000 non-null  object
 59  promotion_effectiveness    1000000 non-null  object
 60  promotion_channel          1000000 non-null  object
 61  promotion_target_audience  1000000 non-null  object
 62  customer_zip_code          1000000 non-null  int64
 63  customer_city              1000000 non-null  object
 64  customer_state             1000000 non-null  object
 65  store_zip_code             1000000 non-null  int64
 66  store_city                 1000000 non-null  object
 67  store_state                1000000 non-null  object
 68  distance_to_store          1000000 non-null  float64
 69  holiday_season             1000000 non-null  object
 70  season                     1000000 non-null  object
 71  weekend                    1000000 non-null  object
 72  customer_support_calls     1000000 non-null  int64
 73  email_subscriptions        1000000 non-null  object
 74  app_usage                  1000000 non-null  object
 75  website_visits             1000000 non-null  int64
 76  social_media_engagement    1000000 non-null  object
 77  days_since_last_purchase   1000000 non-null  int64
dtypes: float64(16), int64(24), object(38)
memory usage: 595.1+ MB

In [14]:
df['loyalty_program'] = df['loyalty_program'].map({'Yes': True, 'No': False})
df['churned'] = df['churned'].map({'Yes': True, 'No': False})
df['holiday_season'] = df['holiday_season'].map({'Yes': True, 'No': False})
df['weekend'] = df['weekend'].map({'Yes': True, 'No': False})
df['email_subscriptions'] = df['email_subscriptions'].map({'Yes': True, 'No': False})
df['transaction_date'] = pd.to_datetime(df['transaction_date'])

In [7]:
print(df.isnull().sum())

customer_id                  0
age                          0
gender                       0
income_bracket               0
loyalty_program              0
membership_years             0
churned                      0
marital_status               0
number_of_children           0
education_level              0
occupation                   0
transaction_id               0
transaction_date             0
product_id                   0
product_category             0
quantity                     0
unit_price                   0
discount_applied             0
payment_method               0
store_location               0
transaction_hour             0
day_of_week                  0
week_of_year                 0
month_of_year                0
avg_purchase_value           0
purchase_frequency           0
last_purchase_date           0
avg_discount_used            0
preferred_store              0
online_purchases             0
in_store_purchases           0
avg_items_per_transaction    0
avg_transaction_value        0
total_returned_items         0
total_returned_value         0
total_sales                  0
total_transactions           0
total_items_purchased        0
total_discounts_received     0
avg_spent_per_category       0
max_single_purchase_value    0
min_single_purchase_value    0
product_name                 0
product_brand                0
product_rating               0
product_review_count         0
product_stock                0
product_return_rate          0
product_size                 0
product_weight               0
product_color                0
product_material             0
product_manufacture_date     0
product_expiry_date          0
product_shelf_life           0
promotion_id                 0
promotion_type               0
promotion_start_date         0
promotion_end_date           0
promotion_effectiveness      0
promotion_channel            0
promotion_target_audience    0
customer_zip_code            0
customer_city                0
customer_state               0
store_zip_code               0
store_city                   0
store_state                  0
distance_to_store            0
holiday_season               0
season                       0
weekend                      0
customer_support_calls       0
email_subscriptions          0
app_usage                    0
website_visits               0
social_media_engagement      0
days_since_last_purchase     0
dtype: int64

In [8]:
df.duplicated().sum()

0

# Creating Sales Data

In [ ]:
df['sales'] = df['unit_price'] * df['quantity']

In [ ]:
# List of sales-related columns
sales_columns = [
    'transaction_id', 'transaction_date', 'product_id', 'product_category', 
    'quantity', 'unit_price', 'discount_applied','sales', 'total_sales', 'store_location',
    'total_transactions', 'avg_transaction_value', 'avg_purchase_value', 
    'purchase_frequency', 'avg_items_per_transaction', 'total_items_purchased', 
    'total_returned_items', 'total_returned_value', 'total_discounts_received', 
    'avg_discount_used', 'max_single_purchase_value', 'min_single_purchase_value'
]

# Create new DataFrame with only sales-related columns
sales_df = df[sales_columns]

# Display the first few rows of the new DataFrame to verify
sales_df.head()
sales_df.to_csv(r'/Users/Jamie/OneDrive/Documents/python_ws/project_delta/data/processed_data/sales_data.csv')

# Creating Customer information Data

In [16]:
customer_information_columns = [ 'customer_id', 'age', 'gender', 'income_bracket', 'loyalty_program', 'membership_years', 'churned', 'marital_status', 'number_of_children', 'education_level', 'occupation'
]

# Create new DataFrame with only sales-related columns
customer_information_df = df[customer_information_columns]

# Display the first few rows of the new DataFrame to verify
customer_information_df.head()
customer_information_df.to_csv(r'/Users/Jamie/OneDrive/Documents/python_ws/project_delta/data/processed_data/customer_information_data.csv')

# Creating customer behaviour data

In [17]:
customer_behaviour_columns =  ['avg_purchase_value','purchase_frequency','last_purchase_date','avg_discount_used','preferred_store','online_purchases','in_store_purchases','avg_items_per_transaction','avg_transaction_value','total_returned_items','total_returned_value'
]


# Create new DataFrame with only sales-related columns
customer_behaviour_df = df[customer_behaviour_columns]

# Display the first few rows of the new DataFrame to verify
customer_behaviour_df.head()
customer_behaviour_df.to_csv(r'/Users/Jamie/OneDrive/Documents/python_ws/project_delta/data/processed_data/customer_behaviour_data.csv')